### ISSUE TITLE
Multi Download Crash

### ISSUE THREAD

**Issue by phinfinity** [jujojujo2003/AnDCpp#5]
I tried to download one file and then after it started I clicked on another file (with the intention of Queueing it) and the app crashed.
first file which worked fine was amazonProductCrawl.zip second file which crashed app was chi96.zip
stack-trace:

```
I/System.out(21504): 1383727204110:Connected to :HubName : SuperNova
I/System.out(21504): 1383727204113:Supports : NoGetINFO NoHello UserCommand UserIP2 
I/System.out(21504): 1383727204150:Hello : asdandcphi
I/System.out(21504): 1383727204152:com.phinmadvader.andcpp.DCPPService$MyUserHandler@41fc2cc0
I/System.out(21504): 1383727204152:com.phinmadvader.andcpp.DCPPService$MyUserHandler@41fc2cc0
I/System.out(21504): 1383727204152:com.phinmadvader.andcpp.DCPPService$MyBoardMessageHandler@41fc3878
I/System.out(21504): 1383727204152:com.phinmadvader.andcpp.DCPPService$MySearchHandler@41fc4048
I/System.out(21504): 1383727204153:com.phinvader.libjdcpp.UsersHandler@41fc21e0
I/System.out(21504): 1383727204153:com.phinvader.libjdcpp.UsersHandler@41fc21e0
I/System.out(21504): 1383727204153:com.phinmadvader.andcpp.DCPPService$MyBoardMessageHandler@41fc3878
I/System.out(21504): 1383727204153:com.phinvader.libjdcpp.DCHandlers$MainDownloadHandler@41fc2a08
E/YEAH HERE WOTH (21504): 115
E/YEah shud be done(21504): done
I/System.out(21504): 1383727207230:iiit-h Tag:null share_size:0
D/download_file_list(21504): Timeout reached : 10020
D/download_file_list(21504): Got download status as : null
I/System.out(21504): 1383727219130:WebMiningDataset Tag:null share_size:0
I/System.out(21504): 1383727219143:in DCRevconnectConnectToMe : asdandcphi 10.2.4.134:37957
I/System.out(21504): 1383727219162:GOT MYNICK
I/System.out(21504): 1383727219228:Download Complete/storage/emulated/0/.andcpp/file_list_WebMiningDataset_1383727219130.xmlCOMPLETED
I/SIZE    (21504): 61587775938
E/PATH    (21504): WebMining\amazonProductCrawl.zip
I/System.out(21504): 1383727226293:WebMiningDataset Tag:null share_size:0
I/System.out(21504): 1383727226303:in DCRevconnectConnectToMe : asdandcphi 10.2.4.134:37957
I/System.out(21504): 1383727226335:GOT MYNICK
E/PATH    (21504): WebMining\chi96.zip
I/System.out(21504): 1383727237312:WebMiningDataset Tag:null share_size:0
W/dalvikvm(21504): threadid=24: thread exiting with uncaught exception (group=0x41b42700)
E/AndroidRuntime(21504): FATAL EXCEPTION: Thread-708
E/AndroidRuntime(21504): java.lang.NullPointerException
E/AndroidRuntime(21504):    at com.phinmadvader.andcpp.DCPPService$DownloadObject.is_finished(DCPPService.java:125)
E/AndroidRuntime(21504):    at com.phinmadvader.andcpp.DCPPService$2.run(DCPPService.java:202)
E/AndroidRuntime(21504):    at java.lang.Thread.run(Thread.java:841)
W/ActivityManager( 2863):   Force finishing activity com.phinmadvader.andcpp/.ConnectActivity
I/Process (21504): Sending signal. PID: 21504 SIG: 9
```

**Comment by madhavanmalolan** [comment]
Unable to reproduce the error.
Multi download puts a notification saying "complete" (Will look into that).
But the 2nd download is neither queued nor does it crash with a Null Ptr Error

**Comment by madhavanmalolan** [comment]
Download queue works fine, error with the notification system.
